# Generated by Django 5.0.6 on 2024-06-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_cart_created_at_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
